version: '3'
services:
  server:
    build: ./
    environment:
      - HOST=0.0.0.0
      - PORT=80
      - MYSQLHOST=35.223.39.16
      - MYSQLUSER=root
      - MYSQLPASS=root
      - MYSQLDB=KITE
      - MYSQLCOL=hash,timeOfDeath,remainingDownloads,password,storageAddress, numberOfFiles, totalByteSize
    volumes:
      - ./Backend:/app/Backend
    ports:
      - "80:80"
    command: "npm run start"