version: '3'
services:
  # mysql:
  #   image: mysql
  #   environment:
  #     - MYSQL_ROOT_PASSWORD=example
  #   volumes:
  #     - ./sql:/docker-entrypoint-initdb.d/
  server:
    build: ./
    environment:
      - HOST=0.0.0.0
      - PORT=8080
      - MYSQLHOST=35.223.39.16
      - MYSQLUSER=root
      - MYSQLPASS=root
      - MYSQLDB=KITE
      - MYSQLCOL=hash,timeOfDeath,remainingDownloads,password,storageAddress
    volumes:
      - ./backend:/app/Backend
    ports:
      - "8080:8080"
