version: '3'
services:
  server:
    build: ./Backend
    container_name: backend
    environment:
      - HOST=0.0.0.0
      - PORT=80
      - MYSQLHOST=35.223.39.16
      - MYSQLUSER=root
      - MYSQLPASS=root
      - MYSQLDB=KITE
      - MYSQLCOL=hash,timeOfDeath,remainingDownloads,password,storageAddress, numberOfFiles, totalByteSize
    volumes:
      - ./Backend:/app/Backend
    command: "npm run start"
  frontend:
    build: ./Frontend
    container_name: frontend
    volumes:
      - ./Frontend/src:/app/src
  nginx:
    image: nginx:alpine
    container_name: nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "80:80"