version: '3'
services:
  # mysql:
  #   image: mysql
  #   environment:
  #     - MYSQL_ROOT_PASSWORD=example
  #   volumes:
  #     - ./sql:/docker-entrypoint-initdb.d/
  server:
    build: ./server
    environment:
      - HOST=0.0.0.0
      - PORT=80
      - MYSQLHOST=35.223.39.16
      - MYSQLUSER=root
      - MYSQLPASS=root
      - MYSQLDB=KITE
      - MYSQLCOL=hash,timeOfDeath,remainingDownloads,password,storageAddress
    volumes:
      - ./server/backend:/app/backend
      - ./server/frontend:/app/frontend
    ports:
      - "80:80"
